service: long-function-II

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  timeout: 60

functions:
  hello:
    handler: handler.run
    events:
      - http:
          path: hola
          method: get
          cors: true
