service: long-function

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  timeout: 60

functions:
  hello:
    handler: handler.run
    events:
      - sqs: arn:aws:sqs:us-west-2:596445984235:otra-queue.fifo
      - http:
          path: hola
          method: get
          cors: true